{% set name = "junn" %}
{% set version = "0.0.1.dev1" %}
{% set sha256 = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # fn: {{ name }}-{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: {{ sha256 }}
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  build:
    - python =3.9
    - pip
    - flit-core
  run:
    - python =3.9
    - numpy
    - scipy
    - scikit-image
    - jsonpickle
    - roifile
    - tifffile
    - keras_nvidia_statistics
    - tunable
    - junn-predict

test:
  imports:
    - junn.predict
    - junn.train

about:
  home: https://github.com/modsim/junn
  license: BSD-2-Clause
  license_family: BSD
  summary: 'junn'
  description: |
    junn
  doc_url: https://github.com/modsim/junn
  dev_url: https://github.com/modsim/junn

extra:
  recipe-maintainers:
    - csachs
