{% set name = "junn-predict" %}
{% set version = "0.0.1.dev1" %}
{% set sha256 = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # fn: {{ name }}-{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: {{ sha256 }}
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  build:
    - python =3.8
    - pip
    - flit-core
  run:
    - python =3.8
    - numpy
    - scipy
    - scikit-image
    - opencv
    - jsonpickle
    - colorlog
    - tqdm
    - tifffile
    - roifile
    - pilyso-io
    - tunable

test:
  imports:
    - junn_predict

about:
  home: https://github.com/modsim/junn
  license: BSD-2-Clause
  license_family: BSD
  summary: 'junn'
  description: |
    junn
  doc_url: https://github.com/modsim/junn
  dev_url: https://github.com/modsim/junn

extra:
  recipe-maintainers:
    - csachs
